layout: sidebar
style: light
theme: jekyll-theme-architect

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

repository: baptistehugot/baptistehugot.github.io

title: [The title of your site]
description: [A short description of your site's purpose]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
      - baptistehugot.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  linkedin: BaptisteHugot
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: BaptisteHugot
  # youtube: your_username
  # instagram: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://www.baptistehugot.cf/