layout: sidebar
style: dark

# Google Analytics
# google_analytics: your_id

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

repository: baptistehugot/baptistehugot.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 18
  exclude:
    forks: true
    projects:
      - baptistehugot.github.io
      - BaptisteHugot

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  linkedin: BaptisteHugot
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: BaptisteHugot
  # youtube: your_username
  # instagram: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://www.baptistehugot.com/
